language: python

matrix:
  include:
    - os: linux
      dist: xenial
    - os: osx
      osx_image: xcode7.2
  
python: 3.7

install:
  - pip install -r requirements_dev.txt
  - pip install -e .
  
script:
  - pytest --cov=functions
  
after_success:
  - coveralls
