language: python

matrix:
  include:
    - os: linux
      dist: xenial
      python: 3.7.2
      install:
      - pip install -r requirements_dev.txt
      - pip install -e .
      script:
      - pytest --cov=functions
      after_success:
      - coveralls
    - os: osx
      language: minimal
      install: 
      - pip install pytest
      - pip install coveralls
      - pip install pytest-cov
      - pip install https://github.com/matteocao/learning-good-practices/archive/master.zip
      script:
      - pytest --cov=functions
      after_success:
      - coveralls 
