# https://aka.ms/yaml
jobs:
- job: 'Test_linux'
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'

  - script: cmake . 
    displayName: 'building C++'

  - script: python -m pip install --upgrade pip setuptools
    displayName: 'Install tools'

  - script: pip install -r requirements_dev.txt
    displayName: 'Install requirements'

  - script: pip install -e .
    displayName: 'Install current environment'

  - script: python scripts/add_script.py
    displayName: 'Try run script'

  - script: pytest tests/
    displayName: 'Test with pytest'

  - script: python setup.py sdist bdist_wheel
    displayName: 'build the wheel'

  - task: CopyFiles@2
    displayName: 'copy files'
    inputs:
      contents: 'dist/*'
      targetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'create download link'
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'wheel'


- job: 'Test_mac'
  pool:
    vmImage: 'macOS-10.13'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'

  - script: cmake .
    displayName: 'building C++'

  - script: python -m pip install --upgrade pip setuptools
    displayName: 'Install tools'

  - script: pip install -r requirements_dev.txt
    displayName: 'Install requirements'

  - script: pip install -e .
    displayName: 'Install current environment'

  - script: python scripts/add_script.py
    displayName: 'Try run script'

  - script: pytest tests/
    displayName: 'Test with pytest'

  - script: python setup.py sdist bdist_wheel
    displayName: 'build the wheel'

  - task: CopyFiles@2
    displayName: 'copy files'
    inputs:
      contents: 'dist/*'
      targetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'create download link in summary'
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'wheel'


- job: 'Test_win'
  pool:
    vmImage: 'vs2017-win2016'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'


  - script: cmake . -G "Visual Studio 15 2017 Win64"
    displayName: 'building C++'

  - script: python -m pip install --upgrade pip setuptools
    displayName: 'Install tools'

  - script: pip install -r requirements_dev.txt
    displayName: 'Install requirements'

  - script: pip install -e .
    displayName: 'Install current environment'

  - script: python scripts/add_script.py
    displayName: 'Try run script'

  - script: pytest tests/
    displayName: 'Test with pytest'

  - script: python setup.py sdist bdist_wheel
    displayName: 'build the wheel'

  - task: CopyFiles@2
    displayName: 'copy files'
    inputs:
      contents: 'dist/*'
      targetFolder: '$(Build.ArtifactStagingDirectory)'

  - task: PublishBuildArtifacts@1
    displayName: 'create download link in summary'
    inputs:
      pathToPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: 'wheel'
       

  # other options: 'macOS-10.13', 'vs2017-win2016'
  # Add additional tasks to run using each Python version in the matrix above
