# https://aka.ms/yaml
jobs:
- job: 'Test_linux'
  pool:
    vmImage: 'ubuntu-16.04'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'

  - script: |
      mkdir build
      cd build
      cmake ..
      cmake --build . --config Release --target check

  - script: python -m pip install --upgrade pip setuptools
    displayName: 'Install tools'

  - script: pip install -r requirements_dev.txt
    displayName: 'Install requirements'

  - script: pip install -e .
    displayName: 'Install current environment'

  - script: pytest
    displayName: 'Test with pytest'

  - script: |
      python setup.py sdist bdist_wheel
      pip install awscli
      aws s3 sync dist/ s3://learning-good-practices/dist
    displayName: 'build and send'
    env:
       AWS_ACCESS_KEY_ID: $(AWS_ACCESS_KEY_ID)
       AWS_SECRET_ACCESS_KEY: $(AWS_SECRET_ACCESS_KEY)



- job: 'Test_mac'
  pool:
    vmImage: 'macOS-10.13'
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'

  - script: python -m pip install --upgrade pip setuptools
    displayName: 'Install tools'

  - script: pip install -r requirements_dev.txt
    displayName: 'Install requirements'

  - script: pip install -e .
    displayName: 'Install current environment'

  - script: pytest
    displayName: 'Test with pytest'


  # other options: 'macOS-10.13', 'vs2017-win2016'
  # Add additional tasks to run using each Python version in the matrix above
