# https://aka.ms/yaml
jobs:
- job: 'Test_linux'
  pool:
    vmImage: 'ubuntu-16.04' 
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'

  - script: python -m pip install --upgrade pip setuptools
    displayName: 'Install tools'

  - script: pip install -r requirements_dev.txt
    displayName: 'Install requirements'

  - script: pip install -e .
    displayName: 'Install current environment'

  - script: pytest
    displayName: 'Test with pytest'

  - script: |
      python setup.py sdist bdist_wheel
      pip install awscli
      aws s3 sync --cache-control max-age=60 dist/ s3://vtext/dist/
    displayName: 'build and send'



- job: 'Test_mac'
  pool:
    vmImage: 'macOS-10.13' 
  strategy:
    matrix:
      Python36:
        python.version: '3.6'
      Python37:
        python.version: '3.7'

  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '$(python.version)'

  - script: python -m pip install --upgrade pip setuptools
    displayName: 'Install tools'

  - script: pip install -r requirements_dev.txt
    displayName: 'Install requirements'

  - script: pip install -e .
    displayName: 'Install current environment'

  - script: pytest
    displayName: 'Test with pytest'


  # other options: 'macOS-10.13', 'vs2017-win2016'
  # Add additional tasks to run using each Python version in the matrix above